### ISSUE TITLE
version 4.2.0 not tagget

### ISSUE THREAD

**Issue by edaojs** [fb55/domhandler#507] opened 2021-04-16 11:59 UTC
can't install it with npm

run:
npm view domhandler
![Captura de tela de 2021-04-16 09-09-32](https://user-images.githubusercontent.com/61250724/115022240-81344680-9e93-11eb-8195-36d702829399.png)

**Comment by fb55** [comment] 2021-04-16 18:43
Duplicate of #506. Tl;dr npm seems to have some issues replicating package versions.

**Closed** 2021-04-16 18:43 UTC
